# Playbook To install the Nginx Using Client Local Nginx Folder

--- 
  - name: Playbook To Install NGINX using Client Local Folder
    hosts: Web
    tasks:
        - name: Update the server 
          shell: apt update -y

        - name: Git Clone
          shell: cd /tmp && git clone https://github.com/mavrick202/dockertest1.git

        - name: Install Nginx
          apt: >
             name=nginx
             state=present

        - name: Copy the files to Index Destination Folder
          copy: >
            src=/tmp/dockertest1/index.html
            dest=/var/www/html/index.nginx-debian.html
            remote_src=yes
            owner=root
            group=root
            mode=0644

          notify:
           - restart nginx    

        - name: copy the style files to Destination folder
          copy: > 
            src=/tmp/dockertest1/style.css
            dest=/var/www/html/style.css
            remote_src=yes
            owner=root
            group=root
            mode=0644

          notify:
            - restart nginx  

        - name: copy the javascript file to thye Destination folder
          copy: > 
            src=/tmp/dockertest1/scorekeeper.js
            dest=/var/www/html/scorekeeper.js
            remote_src=yes
            owner=root
            group=root
            mode=0644

          notify:
            - restart nginx  

        - name: Delete Git Clone
          shell: rm -rf cd /tmp/dockertest1

    handlers:
      - name: restart nginx
        command: service nginx restart
